version: '3'

vars:
  CONFIGURATION: Debug

tasks:
  build:
    cmds:
      - |-
        xcodebuild \
          -project ./Koto.xcodeproj \
          -scheme Koto \
          -configuration {{.CONFIGURATION}} \
          CONFIGURATION_BUILD_DIR="$(pwd)/build/\$(CONFIGURATION)"

  build:release:
    cmds:
      - task: build
        vars:
          CONFIGURATION: Release

  clean:
    cmd: rm -rf ./build

  install:
    deps: [build]
    cmds:
      - cp -R ./build/{{.CONFIGURATION}}/Koto.app ~/Library/Input\ Methods

  install:release:
    deps:
      - build:release
    cmds:
      - task: install
        vars:
          CONFIGURATION: Release

  uninstall:
    cmds:
      - rm -rf ~/Library/Input\ Methods/Koto.app
      - task: stop

  stop:
    cmds:
      - pkill Koto

  fmt:
    cmd: swift-format format --recursive --in-place .
