version: '3'

tasks:
  build:
    silent: true
    cmds:
      - |-
        xcodebuild \
          -project ./Koto.xcodeproj \
          -scheme Koto \
          -configuration Debug \
          CONFIGURATION_BUILD_DIR="$(pwd)/build/\$(CONFIGURATION)"

  install:
    silent: true
    deps: [build]
    cmds:
      - rm -rf ~/Library/Input\ Methods/Koto.app
      - cp -R ./build/Debug/Koto.app ~/Library/Input\ Methods

  stop:
    silent: true
    cmds:
      - pkill Koto

  fmt:
    silent: true
    cmd: swift-format format --recursive --in-place .
