name: ghasec

permissions: {}

defaults:
  run:
    shell: bash

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ghasec:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Run ghasec
        uses: koki-develop/ghasec-action@2810775d2a300cb3fd9583c36c05b5ee3310c5b8 # v1.1.1
        with:
          github-token: ${{ github.token }}
          online: true
