name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build
        run: |
          xcodebuild \
            -project ./Koto.xcodeproj \
            -scheme Koto \
            -configuration Release \
            -arch arm64 -arch x86_64 \
            ONLY_ACTIVE_ARCH=NO \
            CONFIGURATION_BUILD_DIR="$(pwd)/build/\$(CONFIGURATION)" \
            CODE_SIGNING_ALLOWED=NO
          mkdir -p ./tmp/app
          mv ./build/Release/Koto.app ./tmp/app/

      - name: Build Package
        run: |
          xcrun pkgbuild \
            --root ./tmp/app \
            --component-plist ./pkg.plist \
            --identifier me.koki.inputmethod.Koto \
            --install-location '/Library/Input Methods' \
            ./tmp/tmp.pkg

      - name: Build Installer
        run: |
          xcrun productbuild \
            --distribution distribution.xml \
            --package-path ./tmp \
            ./tmp/Koto.pkg

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Koto.pkg
          path: ./tmp/Koto.pkg

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: Koto.pkg
          path: ./tmp
      - uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: ./tmp/Koto.pkg

  release-cask:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Checkout homebrew-tap
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: koki-develop/homebrew-tap
          path: homebrew-tap
          token: ${{ secrets.TAP_GITHUB_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: Koto.pkg
          path: ./tmp

      - name: Metadata
        id: metadata
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          echo "sha256=$(shasum -a 256 ./tmp/Koto.pkg | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "desc=$(gh repo view $GITHUB_REPOSITORY --json description --jq .description)" >> $GITHUB_OUTPUT

      - name: Build Homebrew Cask
        uses: ./.github/actions/build-cask
        with:
          version: ${{ steps.metadata.outputs.version }}
          sha256: ${{ steps.metadata.outputs.sha256 }}
          desc: ${{ steps.metadata.outputs.desc }}
          output-path: ./homebrew-tap/Casks/koto.rb

      - name: Update Homebrew Cask
        working-directory: homebrew-tap
        env:
          KOTO_VERSION: ${{ steps.metadata.outputs.version }}
        run: |
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./Casks/koto.rb
          git commit -m "Brew cask update for koto version v${KOTO_VERSION}"
          git push origin main
